<a href="https://colab.research.google.com/github/farelagustin/2026_kecerdasan_buatan/blob/main/Jobsheet_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Jobsheet 02: Operasi Matematika, Vektor, dan Matriks

Latihan

1. Tipe Data Python

a. Cek tipe Data

In [2]:
var = 123
print(type(var))

<class 'int'>


b. Tipe data String

In [7]:
a = '123'
b = '3.4'
c = "Data String"
print(type(c))

<class 'str'>


c. Tipe data numerik

In [8]:
var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))

<class 'float'>


In [9]:
print(f1)

345.0


In [10]:
sum = var1 + var2
print(sum)

379.5


In [11]:
var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)

34


In [12]:
print(i2)

12


d. Tipe data Boolean

In [13]:
print(var1 == var2)

False


In [14]:
print(var1 < var2)

False


In [15]:
print(var1 > var2)

True


In [16]:
print(var1 != var2)

True


e. Tipe data List

In [17]:
list = ["belajar dasar python", 2023, 3.8, True]
print(list)

['belajar dasar python', 2023, 3.8, True]


In [18]:
print(list[3])

True


In [19]:
print(list[1:3])

[2023, 3.8]


In [20]:
print(len(list))

4


2. Operasi matematika menggunakan python

a. mendapatkan nilai minimum dan maksimum

In [21]:
x = min(5, 10, 25)
y = max(6, 12, 18)
print(x)
print(y)

5
18


b. Mendapatkan nilai absolut

In [29]:
x = abs(-7.25)
print(x)

7.25


c. Mendapatkan nilai pangkat

In [ ]:
import math
x = math.pow(4,3)
print(x)

d. Mendapatkan nilai akar

In [28]:
import math
x = math.sqrt(64)
print(x)

8.0


e. Mendapatkan nilai pembulatan

In [25]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x)
print(y)

2
1


f. Mendapatkan nilai konstanta (PI)

In [23]:
import math
x = math.pi
print(x)

3.141592653589793


3. Menggunakan Fungsi MATH

In [52]:
# Menghitung Sinus
print(math.sin(math.pi/2))
# Menghitung kosinus
print(math.cos(0))
# Menghitung tangen
print(math.tan(math.radians(45)))
# Mengubah sudut dari radian ke derajat.
print(math.degrees(math.pi))

# Menghitung logaritma natural (basis $e$) secara default, atau basis tertentu.
print(math.log(10))     # Logaritma natural dari 10
print(math.log(8, 2))   # Logaritma basis 2 dari 8
# Menghitung logaritma basis 10.
print(math.log10(100))

# Menghitung jarak Euclidean antara dua titik (misal titik A ke titik B).
titik1 = (0, 0)
titik2 = (3, 4)
print(math.dist(titik1, titik2))

# Menghitung sisa bagi (modulo) untuk bilangan desimal (float).
print(math.fmod(20, 3))
print(math.fmod(5.5, 2))

# Menghitung nilai faktorial (n!).
print(math.factorial(5)) # 5*4*3*2*1

# Menghitung permutasi (jumlah cara memilih $k$ objek dari $n$ tanpa pengulangan dan memperhatikan urutan).
print(math.perm(5, 2))

# Menghitung fungsi Gamma (sering disebut faktorial yang diperluas untuk bilangan desimal, di mana Gamma(n) = (n-1)!).
print(math.gamma(5)) # Sama dengan factorial(4)

# Mengecek apakah sebuah nilai adalah NaN (Not a Number/Bukan Angka).
angka_aneh = float('nan')
print(math.isnan(angka_aneh))

1.0
1.0
0.9999999999999999
180.0
2.302585092994046
3.0
2.0
5.0
2.0
1.5
120
20
24.0
True


4. Operasi matriks dan vektor dengan python

a. Membuat matriks di python

In [30]:
import numpy as np
A = np.array([[80, 30, 25],
              [50, 20, 10]])
B = np.array([[30, 60, 15],
              [10, 30, 30]])

hasil = A + B
print(hasil)

[[110  90  40]
 [ 60  50  40]]


b. Melakukan operasi dot product

In [31]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)
print(hasil)

2025


c. Melakukan operasi cross product

In [33]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)
print(Hasil)

[-305 -110  350]


Tugas Praktikum 01

In [39]:
import numpy as np
A = np.array([[3, 1],
             [2, 0]])
B = np.array([[2, 1],
              [1, -1]])
C = np.array([[-1, 1, 2],
              [2, 0, -1]])
# A x B
a = np.cross(A, B)
# B . C
b = np.dot(B, C)

print(f"a. A x B = {a}")
print(f"b. B . C = \n {b} \n")

a. A x B = [ 1 -2]
b. B . C = 
 [[ 0  2  3]
 [-3  1  3]] 



/tmp/ipykernel_768/2390864711.py:9: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  a = np.cross(A, B)


Tugas Praktikum 02

In [42]:
import math

# 6!
soal_a = math.factorial(6)
# 8! / 5!
soal_b = math.factorial(8) / math.factorial(5)

print(f"a. 6! = {soal_a}")
print(f"b. 8! / 5! = {soal_b}")

a. 6! = 720
b. 8! / 5! = 336.0


Tugas Praktikum 03

In [43]:
import numpy as np
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Menentukan Panjang Masing-masing Vektor (Norm)
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

# Perkalian Titik (A.B)
dot_product = np.dot(A, B)

# Perkalian Silang (AxB)
cross_product = np.cross(A, B)

print(f"Panjang Vektor A: {panjang_A:.2f}")
print(f"Panjang Vektor B: {panjang_B:.2f}")
print(f"Hasil Perkalian Titik (A.B): {dot_product}")
print(f"Hasil Perkalian Silang (AxB): {cross_product}")

Panjang Vektor A: 9.11
Panjang Vektor B: 12.41
Hasil Perkalian Titik (A.B): 58
Hasil Perkalian Silang (AxB): [ 24  79 -51]
